version: '3.8'

services:
  bot:
    build: .
    container_name: emotions-translator-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge