version: '3.8'

services:
  bot:
    build: .
    container_name: emotions-translator-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network

  redis:
    image: redis:7-alpine
    container_name: emotions-translator-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bot-network
    command: redis-server --appendonly yes

networks:
  bot-network:
    driver: bridge

volumes:
  redis-data: