version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: emotions-analytics-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-analytics_secret_2024}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bot-network

  bot:
    build: .
    container_name: emotions-translator-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: analytics
      DB_USER: analytics_user
      DB_PASSWORD: ${DB_PASSWORD:-analytics_secret_2024}
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  bot-network:
    driver: bridge